# Generated by Django 3.0.2 on 2020-01-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
